class Config:
    MAX_IMAGES = 8
    ALLOWED_FORMATS = {'jpeg', 'jpg', 'png'}
    KUNDALI_WEIGHT = 0.8
    PERSONAL_WEIGHT = 1-KUNDALI_WEIGHT
    TOTAL_GUN = 36
    MAX_MATCHES = 10
    PROFILE_TABLE_SCHEMA = ""
    PROFILE_TABLE_DATABASE = ""
    PROFILE_TABLE_WAREHOUSE = ""
    MATCHING_TABLE_SCHEMA = ""
    MATCHING_TABLE_DATABASE = ""
    MATCHING_TABLE_WAREHOUSE = ""

config = Config()