services:
  backend-service:
    build: ./service-backend
    ports:
      - "8080:8080"
    depends_on:
      - kundali-service

  kundali-service:
    build: ./service-kundali
    ports:
      - "8000:8000"