services:
  backend-service:
    build: ./service-backend
    ports:
      - "8040:8040"
    depends_on:
      - sql-service
      - kundali-service
    environment:
      DEPLOYMENT_ENV: local
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ~/.aws:/root/.aws:ro

  kundali-service:
    build: ./service-kundali
    ports:
      - "8000:8000"

  sql-service:
    build: ./service-sqlite
    ports:
      - 8030:8030
    volumes:
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  sqlite_data: