version: "3.8"

services:
  frontend-service:
    build: ./service-frontend
    platform: linux/amd64
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - backend-service

    restart: unless-stopped 
  backend-service:
    build:
      context: ./service-backend
    platform: linux/amd64
    ports:
      - "127.0.0.1:8040:8040"
    depends_on:
<<<<<<< Updated upstream
=======
      - sql-service
      - sql-service
>>>>>>> Stashed changes
      - kundali-service
      - sql-service
      - mbti-service
    environment:
      DEPLOYMENT_ENV: develop
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped

  kundali-service:
    build: 
      context: ./service-kundali
    platform: linux/amd64
    ports:
      - "8000:8000"

  sql-service:
    build: 
      context: ./service-sqlite
    platform: linux/amd64
    ports:
      - "8030:8030"
    volumes:
      - ./data:/app/data
      - ./sqlite_service.db:/app/sqlite_service.db
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - sqlite_data:/app/data  # Persist SQLite database data
    restart: unless-stopped
    

  mbti-service:
    build: 
      context: ./service-mbti
    platform: linux/amd64
    ports:
      - "8010:8010"