services:
  backend-service:
    build: ./service-backend
    ports:
      - "8080:8080"
    depends_on:
      - kundali-service
    environment:
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ~/.aws:/root/.aws:ro

  kundali-service:
    build: ./service-kundali
    ports:
      - "8000:8000"