services:
  backend-service-amd64:
    build:
      context: ./backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - kundali-service-amd64

  kundali-service-amd64:
    build: 
      context: ./kundali_service
    platform: linux/amd64
    ports:
      - "8000:8000"