services:
  backend-service-amd64:
    build:
      context: ./service-backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - kundali-service-amd64

  kundali-service-amd64:
    build: 
      context: ./service-kundali
    platform: linux/amd64
    ports:
      - "8000:8000"