services:
  frontend-service:
    build: ./service-frontend
    #platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-service

    restart: unless-stopped 

  backend-service:
    build: ./service-backend
    ports:
      - "8040:8040"
    depends_on:
      - sql-service
      - kundali-service
    environment:
      DEPLOYMENT_ENV: local
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ~/.aws:/root/.aws:ro

  kundali-service:
    build: ./service-kundali
    ports:
      - "8000:8000"

  mbti-service:
    build: ./service-mbti
    ports:
      - "8010:8010"

  sql-service:
    build: ./service-sqlite
    ports:
      - 8030:8030
    volumes:
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  sqlite_data: